export const UPVOTE_ISSUE_REQUEST = 'UPVOTE_ISSUE_REQUEST';
export const UPVOTE_ISSUE_SUCCESS = 'UPVOTE_ISSUE_SUCCESS';
export const UPVOTE_ISSUE_FAILURE = 'UPVOTE_ISSUE_FAILURE';

export const DOWNVOTE_ISSUE_REQUEST = 'DOWNVOTE_ISSUE_REQUEST';
export const DOWNVOTE_ISSUE_SUCCESS = 'DOWNVOTE_ISSUE_SUCCESS';
export const DOWNVOTE_ISSUE_FAILURE = 'DOWNVOTE_ISSUE_FAILURE';

export const CREATE_NEW_ISSUE_REQUEST = 'CREATE_NEW_ISSUE_REQUEST';
export const CREATE_NEW_ISSUE_SUCCESS = 'CREATE_NEW_ISSUE_SUCCESS';
export const CREATE_NEW_ISSUE_FAILURE = 'CREATE_NEW_ISSUE_FAILURE';

export const DOWNVOTE = 'DOWNVOTE';
export const CREATE_NEW_ISSUE = 'CREATE_NEW_ISSUE';
