export const UPVOTE_ISSUE_REQUEST = 'UPVOTE_ISSUE_REQUEST';
export const UPVOTE_ISSUE_SUCCESS = 'UPVOTE_ISSUE_SUCCESS';
export const UPVOTE_ISSUE_FAILURE = 'UPVOTE_ISSUE_FAILURE';

export const DOWNVOTE = 'DOWNVOTE';
export const CREATE_NEW_ISSUE = 'CREATE_NEW_ISSUE';
